# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=0.43.4
maven_group=com.moulberry.flashback
archives_base_name=flashback

# Dependencies
fabric_version=0.160.7+26.3
